### ISSUE TITLE
Reasons for using colmap

### ISSUE THREAD

**Issue by KeoChi** [AIBluefisher/GraphSfM#16]
Why do you remove openMVG and use colmap? What is the advantage of colmap?

**Comment by AIBluefisher** [comment]
Because there is already another more modular version of my GraphSfM that based on OpenMVG. Besides, I think the code in OpenMVG is a mass and hard to reconstruct. So I tried to use COLMAP.

**Comment by whuaegeanse** [comment]
The codes of OpenMVG is more simple and more readable than that of COLMAP, especially in the module of increment SfM.

**Comment by AIBluefisher** [comment]
In my point of view, from any aspect, OpenMVG is disobeying the rules of software engineering. If you put your sight further, it shouldn't be encouraged to use OpenMVG as a good example in a large project.

**Comment by rperrot** [comment]
Hi @AIBluefisher, 

I'm sad that you choose to forgive OpenMVG. But, if you have some time, could you explain what do you mean by "rules of software engineering" ? We always work with the community to help enhancing the library, and we took as much care as we can to respect some rules of software engineering (documentation, unit testing, code comment, platform testing, respect of the standards, ...). Moreover, we always take into account remarks and suggestions of all the community : the library is develop in some parts with the help of the community and many aspects have been improved with PR or simple suggestions. 

If you can make some propositions to improve the library we would be grateful.

**Comment by AIBluefisher** [comment]
Sorry for my delay. I really appreciate the comtribution OpenMVG has taken to the community of 3D reconstruction. My early work was really encouraged by OpenMVG and you guys. However, when I tried to contribute some of my algorithms to the lib, I found it was really a difficult work. In my opinion, OpenMVG would become a better library if changes are made to these things below:
(1) The code style. Not to offend, but sometimes I really got into crazy when I review the code of OpenMVG: the name of variables(and also some classes) is mixed with underlines, uppercases and lowercases. It would be better to follow some code styles for every contributor and make this project more readable. I believe `Google Code Style` is a good handbook.
(2) Lack of log managemnet. Log system allows us to trace where bugs happened. I would suggest GLOG.
(3) Some functions seem too long to read. There are sufficient comments inside functions, however, I think functions that are too long should be re-considered the implementation.
(4) The design of `SfMData`. I don't know whether it good or not to store all sfm data structures in this struct. But I believe it lacks of encapsulation. I think it's better to use a `Image` class to store data such as features, poses and the 3D points it sees; also a `Camera` class to store data such as intrinsics. It's just my point of view and it might be lots of disagreement with me.
(5) The way that OpenMVG stores its data in local disk. I would like to ask why choose to store them in a json file? It seems convinient for debugging, but it would become a bottleneck when the scale of datasets is very large.
(6) Too many dependencies. It could be convinient to implement some algorithms but also could be really hard to configure this project. Actually, many people have complained about the difficulty to pass the compliling process. I think this project should be simplified at some point.

**Comment by AIBluefisher** [comment]
You may also notice that I'm still maintaining a similar repo(https://github.com/AIBluefisher/EGSfM) that based on OpenMVG, I really hope OpenMVG would be a better project.

**Comment by pmoulon** [comment]
Hello @AIBluefisher,
Thank you for your feedback.

Let me try to provide some answers to the point you have listed.

1) `Code Style`
As you know OpenMVG is a long-running project. The project was created in 2013 and at this time I was a junior developer trying to share my enthusiasm, provide knowledge and tools to the community around photogrammetry. The most recent contributions follow a better design/API and allow more flexibility.
We are aware of this issue and we plan to fix it, but we cannot break the API for a minor release. We are so waiting to do those changes for version 2.0.

2) `Log management`
We are working on this item, see the WIP branch https://github.com/openMVG/openMVG/tree/develop_logger and the open issue related to it https://github.com/openMVG/openMVG/issues/1223

3) `Long functions`
We are trying our best to keep the code concise. As you can see as we are moving along, the code is refactored and becoming more readable. (See IncrementalSfMv1 and the v2).
Feel free to pinpoint the function you are considering too long and we can work together in refactoring. Notice also that the community is working on his free time to contribute to the project, so we must consider that things are always perfectible and could be enhanced by another developer.
As you noticed, comments are there, and this is not the case of all open source projects.

4) `Data Structure`
Thank you for your feedback.
Since we have this data container, users are able to understand and push code in an easier way to OpenMVG.
If there is a lack of encapsulation you can try to make it better.

> also a Camera class to store data such as intrinsics

Perhaps you did not notice, but the sfm_data container is using a Camera class see here https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data.hpp#L25, Intrinsic Base is the Abstract camera class of OpenMVG.

Thank you for sharing your idea about having an `Image` class to store features and poses... OpenMVG concept is about not mixing concepts together (an image is an image) but use an object for what it is designed.
The sfm_data container is really flexible to user customization. If you want to extend it to your purpose it can be done easily. You said you want features encapsulated in an `Image` concept. You can inherit from the `View` and update the `FeatureProvider` to gather data from it... https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data.hpp#L31

5) `Data storage`
OpenMVG store JSON file only for the first step of the pipeline (Initialization of the scene (Views and Intrinsics)). We are doing it this way because it's allowing people to easily discover OpenMVG sfm_data concept and let them customize the values if they need to.
As you are moving along in the SfM pipeline, all the data are then stored in a `binary` format to ensure the fastest read/save operations as possible (see sfm_data.bin, descriptors...).
Moreover, since OpenMVG is providing a mechanism for data abstraction, you can change the storage of the feature if you need it (see FeatureProvider that you can customize).

Note: Dealing with large scale data is an issue for everyone. Commercial companies can work on those items more `efficiently` since they are paying people to work on those topics. All OpenSource projects are trying their best to provide solutions in their free time for free.

(6) `dependencies`
OpenMVG dependencies are minimal, and we are using them since we don't want to rewrite what is working good out there. The largest dependencies are imageIO (Jpeg,Tiff,PnG...), Eigen and Ceres.

> Actually, many people have complained about the difficulty to pass the compliling process. I think this project should be simplified to some point.

OpenMVG is trying is best to help the community, we are providing a how-to build guide https://github.com/openMVG/openMVG/blob/develop/BUILD.md, we are providing a Dockerfile to ease build in a container, we are providing CI for Linux, MacOs, and Windows to ensure our code builds on multiple platforms.
We are open to suggestion, if you find some idea to simplify the process, we would be happy.

*General feedback:*

We are sorry to hear that those points were disappointing for you.
The OpenSource community is also hear to listen and bounce back.
We suggest you leverage the as an opportunity to contribute and fix some of the issue with the community.

We always welcome positive criticism and we are really open to provide the best for our community. We can now work on the next step by turning on the light here and work on the code later on.

> You may also notice that I'm still maintaining a similar repo(https://github.com/AIBluefisher/EGSfM) that based on OpenMVG, I really hope OpenMVG would be a better project.

We are aware of your project and we are really happy that you choose OpenMVG for it. We would encourage you to speak about your project on OpenMVG issues in order to let the community test it and help the community to integrate your pipeline in OpenMVG if they see fit.

OpenMVG was created to let people be aware and play with photogrammetry and let them create a new SfM pipeline. It is what you have done and we are really happy that you got this opportunity.

**Comment by whuaegeanse** [comment]
1. Data Structure
To the best I know, Colmap use another class named Reconstruction which is different openMVG's SfMData. In my option, the data structure used in openMVG is more flexible and readable that of Colmap for that the developer can access camera intrinsics, views, poses , tracks and others. Additionally, the data structure named SfMData in openMVG use less memory than that of Colmap because of that Colmap use data structure image to store the coordinates and track id of features, actually not all of the features can triangulate a validate 3d point.

2. Track ID
The process of generating tracks in openMVG is very simple and fast because of using UnionFind alg. Use track id ,combining with the landmark of SfMData,  we know the connected images and the corresponding features. It's very easy to use the unique ids of tracks in different sparse reconstructions aligning sub reconstructions.  On the contrary, it is difficult to implement the same process in Colmap. 

3. Triangulation/Retriangulation tracks
The process of triangulation/retriangulation in Colmap is very complicated, also very stable because of using functions such as creat/continue/merge and ransac based methods to generating robust tracks. But it's not easy to parallel this process,  on the contrary it's very easy for that of openMVG.

**Comment by AIBluefisher** [comment]
> Hello @AIBluefisher,
> Thank you for your feedback.
> 
> Let me try to provide some answers to the point you have listed.
> 
> 1. `Code Style`
>    As you know OpenMVG is a long-running project. The project was created in 2013 and at this time I was a junior developer trying to share my enthusiasm, provide knowledge and tools to the community around photogrammetry. The most recent contributions follow a better design/API and allow more flexibility.
>    We are aware of this issue and we plan to fix it, but we cannot break the API for a minor release. We are so waiting to do those changes for version 2.0.
> 2. `Log management`
>    We are working on this item, see the WIP branch https://github.com/openMVG/openMVG/tree/develop_logger and the open issue related to it [openMVG/openMVG#1223](https://github.com/openMVG/openMVG/issues/1223)
> 3. `Long functions`
>    We are trying our best to keep the code concise. As you can see as we are moving along, the code is refactored and becoming more readable. (See IncrementalSfMv1 and the v2).
>    Feel free to pinpoint the function you are considering too long and we can work together in refactoring. Notice also that the community is working on his free time to contribute to the project, so we must consider that things are always perfectible and could be enhanced by another developer.
>    As you noticed, comments are there, and this is not the case of all open source projects.
> 4. `Data Structure`
>    Thank you for your feedback.
>    Since we have this data container, users are able to understand and push code in an easier way to OpenMVG.
>    If there is a lack of encapsulation you can try to make it better.
> 
> > also a Camera class to store data such as intrinsics
> 
> Perhaps you did not notice, but the sfm_data container is using a Camera class see here https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data.hpp#L25, Intrinsic Base is the Abstract camera class of OpenMVG.
> 
> Thank you for sharing your idea about having an `Image` class to store features and poses... OpenMVG concept is about not mixing concepts together (an image is an image) but use an object for what it is designed.
> The sfm_data container is really flexible to user customization. If you want to extend it to your purpose it can be done easily. You said you want features encapsulated in an `Image` concept. You can inherit from the `View` and update the `FeatureProvider` to gather data from it... https://github.com/openMVG/openMVG/blob/develop/src/openMVG/sfm/sfm_data.hpp#L31
> 
> 1. `Data storage`
>    OpenMVG store JSON file only for the first step of the pipeline (Initialization of the scene (Views and Intrinsics)). We are doing it this way because it's allowing people to easily discover OpenMVG sfm_data concept and let them customize the values if they need to.
>    As you are moving along in the SfM pipeline, all the data are then stored in a `binary` format to ensure the fastest read/save operations as possible (see sfm_data.bin, descriptors...).
>    Moreover, since OpenMVG is providing a mechanism for data abstraction, you can change the storage of the feature if you need it (see FeatureProvider that you can customize).
> 
> Note: Dealing with large scale data is an issue for everyone. Commercial companies can work on those items more `efficiently` since they are paying people to work on those topics. All OpenSource projects are trying their best to provide solutions in their free time for free.
> 
> 1. `dependencies`
>    OpenMVG dependencies are minimal, and we are using them since we don't want to rewrite what is working good out there. The largest dependencies are imageIO (Jpeg,Tiff,PnG...), Eigen and Ceres.
> 
> > Actually, many people have complained about the difficulty to pass the compliling process. I think this project should be simplified to some point.
> 
> OpenMVG is trying is best to help the community, we are providing a how-to build guide https://github.com/openMVG/openMVG/blob/develop/BUILD.md, we are providing a Dockerfile to ease build in a container, we are providing CI for Linux, MacOs, and Windows to ensure our code builds on multiple platforms.
> We are open to suggestion, if you find some idea to simplify the process, we would be happy.
> 
> _General feedback:_
> 
> We are sorry to hear that those points were disappointing for you.
> The OpenSource community is also hear to listen and bounce back.
> We suggest you leverage the as an opportunity to contribute and fix some of the issue with the community.
> 
> We always welcome positive criticism and we are really open to provide the best for our community. We can now work on the next step by turning on the light here and work on the code later on.
> 
> > You may also notice that I'm still maintaining a similar repo(https://github.com/AIBluefisher/EGSfM) that based on OpenMVG, I really hope OpenMVG would be a better project.
> 
> We are aware of your project and we are really happy that you choose OpenMVG for it. We would encourage you to speak about your project on OpenMVG issues in order to let the community test it and help the community to integrate your pipeline in OpenMVG if they see fit.
> 
> OpenMVG was created to let people be aware and play with photogrammetry and let them create a new SfM pipeline. It is what you have done and we are really happy that you got this opportunity.

Thanks for sharing your views. I would like to contribute to this community, but currently I am really busy with my master thesis and ph.D application. My paper that share the idea of GraphSfM is still in reviewing and we may discuss it later at some conference. What's more, your project is really cool and thanks again.

**Comment by pmoulon** [comment]
Best wishes for your master thesis and phD application & good luck for your paper submission.
