### ISSUE TITLE
Does this support GCPs (Ground control points), if not, can you provide guidance on how to implement it here?

### ISSUE THREAD

**Issue by AbegNext** [AIBluefisher/GraphSfM#19]

**Comment by AIBluefisher** [comment]
Do you mean using ground control points to stitch sub map?

**Comment by AbegNext** [comment]
I mean ground control points with known
 georeferenced location and pixel locations in various images for model alignment and also to include them as constraints in the bundle adjustments.

**Comment by AIBluefisher** [comment]
Okay, I also found some useful information on the webpage [https://www.pix4d.com/blog/why-ground-control-points-important](https://www.pix4d.com/blog/why-ground-control-points-important).

(1) Then, with GCPs, we can obtain the absolute scale of point clouds. If we want to align models by ground control points, we might implement it by following the steps below:

1. Suppose each sub-model has some GCPs, thus we can compute the similarity transformation to register the sub-model into world frame / earth frame by 3D-3D correspondences. See function `FindSimilarityTransform` in [https://github.com/AIBluefisher/GraphSfM/blob/dev/src/controllers/sfm_aligner.cpp](https://github.com/AIBluefisher/GraphSfM/blob/dev/src/controllers/sfm_aligner.cpp) for how to compute accurate similarity transformation.

2. With known similarity transformation, all camera poses and 3D points can be transformed into the earth frame by this similarity transformation. 

3. When all sub-models are registered into the earth frame, we can simply put  these sub-models together, as they are already in a global world frame.

I'm not sure whether I totally understand what you want to do. We could discuss it if not. 

(2) For how to include GCPs as constraints in bundle adjustment, I'm not aware of the usage of GCPs in improving the model accuracy. As far as I currently know, we could simply set the ground control points as constant variables in the optimization, because these points can be seen as ground truth and we don't need to optimize these points.
