### ISSUE TITLE
Error on installing 

### ISSUE THREAD

**Issue by jchen706** [AIBluefisher/GraphSfM#22]
![image](https://user-images.githubusercontent.com/32785168/89955088-42613900-dc00-11ea-909d-8d789ca2e457.png)
I got this error in the final step of installing GraphSfM.

**Comment by AIBluefisher** [comment]
This picture shows nothing. Type `make` to show the latest error information.

**Comment by jchen706** [comment]
I think this is a colmap problem, my friend got it install successfully on Ubunutu 16.04, they say is something  with libboost version to be 1.58 in the colmap issues.
I was running on Ubuntu 18.04

**Comment by jchen706** [comment]
the command was make-j8 
![image](https://user-images.githubusercontent.com/32785168/90323544-a9e4f480-df30-11ea-9d22-5a85a847b48c.png)
![image](https://user-images.githubusercontent.com/32785168/90323553-c2550f00-df30-11ea-8b79-0b6bb8a94f60.png)

This is the errors when running on ubuntu 18.04

**Comment by Yzhbuaa** [comment]
It seems the ceres version is not compatible with colmap version, what is your ceres version? I recommend you to use ceres 1.14.0 rather than master branch. The issuse has been discussed in https://github.com/colmap/colmap/issues/905#issuecomment-656169406.  

By the way, using "make" rather than "make -j8" could print out the bugs more clearly.

Have a nice day.

**Comment by jchen706** [comment]
That was the issue thanks.
